# Generated by Django 4.1.3 on 2022-11-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name="board",
            name="column",
            field=models.ManyToManyField(blank=True, null=True, to="trello_app.column"),
        ),
    ]
