# Generated by Django 4.1.3 on 2022-11-21 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0002_column_alter_board_title_board_column"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="column",
        ),
        migrations.AddField(
            model_name="column",
            name="board",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="column",
                to="trello_app.board",
            ),
            preserve_default=False,
        ),
    ]
