# Generated by Django 4.1.3 on 2022-11-23 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="card",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="trello_app.card",
            ),
        ),
    ]
