# Generated by Django 4.1.3 on 2022-11-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0003_alter_comment_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="image",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
    ]
