# Generated by Django 4.1.3 on 2022-11-22 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0004_alter_board_image_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="column",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card",
                to="trello_app.column",
            ),
        ),
    ]
