# Generated by Django 4.1.3 on 2022-11-22 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trello_app", "0005_alter_card_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="favorites",
            field=models.ManyToManyField(
                related_name="favorite", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
