# Generated by Django 4.1.3 on 2022-11-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0005_alter_board_image_alter_board_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
