# Generated by Django 4.1.3 on 2022-11-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0006_board_favorites"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="favorites",
            new_name="favourites",
        ),
    ]
