# Generated by Django 4.1.3 on 2022-11-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0007_alter_board_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
