# Generated by Django 4.1.3 on 2022-11-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0008_alter_board_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
