# Generated by Django 4.1.3 on 2022-11-23 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trello_app", "0011_board_favourites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="favourites",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="favourites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
