# Generated by Django 4.1.3 on 2022-11-23 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trello_app", "0012_alter_board_favourites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="favourites",
            field=models.ManyToManyField(
                blank=True, related_name="favourites", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
