# Generated by Django 4.1.3 on 2022-11-23 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trello_app", "0013_alter_board_favourites"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="archive",
            field=models.ManyToManyField(
                blank=True, related_name="archive", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
